### ISSUE TITLE
Should I be able to add this info to a custom watchface?

### ISSUE THREAD

**Issue by matepek** [bfkeinberg/ciq_aqi_data_field#1]
Hello,

I'm kinda new in this Garmin world and I found your app. I thought if I install i will be able to add it to a custom watchface but I cannot. I am able to see your app in the activities but is shows `N/A`.

My device has version 3.0 [compatibility](https://developer.garmin.com/connect-iq/compatible-devices/). 

If you can tell me where can I access the logs I will try to collect :)

**Comment by bfkeinberg** [comment]
I am a little unclear here. Are you saying that the watch does not list the field as one that you can add to the custom watchface or that you add it and it doesn't work?
Can you add it as a field to the standard watchface?
To answer your question, if you create, under Garmin/Apps/Logs, a file named 8B0E18A1.TXT, then the field will dump logs
into there. Also, which Garmin device is this specifically?

**Comment by matepek** [comment]
I cannot add to the standard watchface, not listed.
I was able to add to some custom activity's widget but it shows `N/A`.

`Garmin/Apps/Logs/8B0E18A1.TXT` on the watch/device, right? Will do tomorrow.

**Comment by bfkeinberg** [comment]
What it sounds like is that it didn't read the air quality info - to troubleshoot - if you check the Garmin Connect app on your phone, does it show that it is connected to your device? It is the phone that actually talks over the network to get air quality info, so that would be the first thing to check.

**Comment by matepek** [comment]
Yes, it is connected to the phone and I can see the data field listed in the garmin connect app.
I'm clueless but I would be happy to solve because I have 1 free info-slot and this is actually a pretty nice info.
(basically the only one I found useful in the whole store : )

Btw, do you have some cool app/data field suggestions? I googled it but.. meh

**Comment by bfkeinberg** [comment]
OK, interesting. Also sometimes it can take fifteen minutes or so before the Garmin decides that it will get data going through to the field. Good data fields, hmm. There's a lot of boring stuff out there, true. Beer counters are not exciting to me. There's one that shows wind direction, which is kind of cool, but he charges for that one now.

**Comment by matepek** [comment]
This is for the custom activity:
![B93F46BB-2E31-4C9D-A02D-3A97966362AE](https://user-images.githubusercontent.com/16504598/111019740-b6143000-83f3-11eb-91cd-66ab20a204d2.JPG)

It is a bit suspicious that is shows `0/2 Added`. I only have one data field, yours.

For watchface there i nothing to show.

I put the text file for there for logging but it is still empty after reinstalling and restarting. Will check it tomorrow.

**Comment by matepek** [comment]
### Update: 

It works as part of an activity widget but cannot select it for watchface. :(

The logfile is still empty.

**Comment by bfkeinberg** [comment]
I think that the logfile is empty because your Garmin never starts the field. Can you select other CIQ data fields for the watchface? Or only the built-in data fields? That would be a clue.

**Comment by bfkeinberg** [comment]
Hey, I'm just wondering if you have any further findings? I'm still curious about having you troubleshoot this, although since I don't have your device I can only guess a little. Is a custom watchface a Connect IQ app? And when you said that the logfile was empty, was that in the case where you could select the data field, as part of an activity widget, or when you could not?

**Comment by matepek** [comment]
Hello,
I've checked. the log file is still empty. As I said if I create an activity and I can add the AirQuality as a data field but cannot ad to the watch face.

**Comment by matepek** [comment]
It's a Descent MK2.

**Comment by bfkeinberg** [comment]
So - is the AQI field the only field that you can't add to the watch face? Can you add a different Connect IQ data field to the watch face, but not this one?

**Comment by matepek** [comment]
I will check it sometime.

**Comment by matepek** [comment]
Hello, I cannot add different Connect IQ data field either.
Tried: 
- Graphical Elevation (Garmin)
- Graphical Hearth Rate (Garmin)

**Comment by bfkeinberg** [comment]
Ok, I guess that answers the question. Connect IQ data fields cannot be
used in this way on watches.

**Comment by bfkeinberg** [comment]
closing now that the text on the app store is updated to reflect this
